
// This file has been generated by the GUI designer. Do not modify.
namespace DupsBegone
{
	public partial class UIQueries
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.VBox vboxDeleteEmptyFolders;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Image image2;
		
		private global::Gtk.Label label5;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DupsBegone.UIQueries
			this.Name = "DupsBegone.UIQueries";
			this.Title = global::Mono.Unix.Catalog.GetString ("UIQueries");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DupsBegone.UIQueries.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vboxDeleteEmptyFolders = new global::Gtk.VBox ();
			this.vboxDeleteEmptyFolders.Name = "vboxDeleteEmptyFolders";
			this.vboxDeleteEmptyFolders.Spacing = 6;
			// Container child vboxDeleteEmptyFolders.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Empty folders found:</b> (Click trash can to delete)");
			this.label4.UseMarkup = true;
			this.vboxDeleteEmptyFolders.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxDeleteEmptyFolders [this.label4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxDeleteEmptyFolders.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("DupsBegone.trashcan_16x16.gif");
			this.hbox1.Add (this.image2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("/some/folder/that/is/empty");
			this.hbox1.Add (this.label5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vboxDeleteEmptyFolders.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxDeleteEmptyFolders [this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox3.Add (this.vboxDeleteEmptyFolders);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vboxDeleteEmptyFolders]));
			w6.Position = 0;
			w1.Add (this.vbox3);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 557;
			this.DefaultHeight = 581;
			this.Show ();
		}
	}
}
